version: '3'
services:
  store:
    image: linuxtips/nginx-prometheus-exporter:1.0.0
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.store.rule=Host('store.biqueiranerd.com.br')"
        - "traefik.http.routers.store.entrypoints=web"
        - "traefik.http.services.store.loadbalancer.server.port=80"
networks:
  traefik-public:
    external: true